run:
  timeout: 5m
  issues-exit-code: 5
  tests: false

output:
  formats:
    - format: colored-line-number
  sort-results: true
  sort-order:
    - severity
    - linter
    - file
  show-stats: true

linters:
  enable-all: false
  enable:
    - copyloopvar # Copyloopvar is a linter detects places where loop variables are copied
    - decorder # Check declaration order and count of types, constants, variables and functions
    - dogsled # Checks assignments with too many blank identifiers (e.g. x, , , _, := f()).
    - dupl # Tool for code clone detection.
    - durationcheck # Check for two durations multiplied together.
    - errchkjson # Checks types passed to the json encoding functions.
    - exhaustive # Check exhaustiveness of enum switch statements.
    - fatcontext # Detects nested contexts in loops.
    - forcetypeassert # Finds forced type assertions.
    - gocheckcompilerdirectives # Checks that go compiler directive comments (//go:) are valid.
    - gochecknoinits # Checks that no init functions are present in Go code.
    - goconst # Finds repeated strings that could be replaced by a constant.
    - gocritic # Provides diagnostics that check for bugs, performance and style issues.
    - godox # Tool for detection of FIXME, TODO and other comment keywords.
    - gofmt # Gofmt checks whether code was gofmt-ed. By default this tool runs with -s option to check for code simplification.
    - gosec # Inspects source code for security problems.
    - makezero # Finds slice declarations with non-zero initial length.
    - misspell # Finds commonly misspelled English words.
    - nilnil # Checks that there is no simultaneous return of nil error and an invalid value.
    - nolintlint # Reports ill-formed or insufficient nolint directives.
    - paralleltest # Detects missing usage of t.Parallel() method in your Go test.
    - perfsprint # Checks that fmt.Sprintf can be replaced with a faster alternative.
    - protogetter # Reports direct reads from proto message fields when getters should be used.
    - reassign # Checks that package variables are not reassigned.
    - rowserrcheck # Checks whether Rows.Err of rows is checked successfully.
    - tagliatelle # Checks the struct tags.
    - testifylint # Checks usage of github.com/stretchr/testify.
    - unconvert # Remove unnecessary type conversions.
    - whitespace # Whitespace is a linter that checks for unnecessary newlines at the start and end of functions, if, for, etc.

linters-settings:
  errcheck:
    exclude-functions:
      - (*github.com/gin-gonic/gin.Context).Error
      - (io.Closer).Close
      - (*go.mongodb.org/mongo-driver/mongo.Client).Disconnect
  godox:
    keywords:
      - TODO
  gofmt:
    simplify: true
    rewrite-rules:
      - pattern: "interface{}"
        replacement: "any"
      - pattern: "a[b:len(a)]"
        replacement: "a[b:]"
  misspell:
    locale: US
    #ignore-words:
    mode: default
  nolintlint:
    allow-unused: false
    require-explanation: true
