version: "3.4"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./data/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: d9aeb352a9c668e8793b2412e895dc72a9260ae4d0e00e0cf624a209f3fff983
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 100s
      retries: 10

  api_service:
    image: api_service
    container_name: api_service
    user: root
    volumes:
      - ./config:/config
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    depends_on:
      mongo:
        condition: service_healthy
