basePath: /api/
consumes:
- application/json
definitions:
  handlers.HandleLoginCommand.LoginResponse:
    properties:
      session:
        type: string
    type: object
  models.LoginCommand:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  models.RequestError:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
host: localhost:80
info:
  contact: {}
  title: SSO API
  version: "1.0"
paths:
  /sessions:
    post:
      parameters:
      - description: User credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.LoginCommand'
      produces:
      - application/json
      responses:
        "200":
          description: Generated session key
          schema:
            $ref: '#/definitions/handlers.HandleLoginCommand.LoginResponse'
        "400":
          description: Received bad request body
          schema:
            $ref: '#/definitions/models.RequestError'
        "404":
          description: User was not found or password is incorrect
          schema:
            $ref: '#/definitions/models.RequestError'
      summary: Log in user with login and password
      tags:
      - sessions
  /sessions/{session}:
    delete:
      parameters:
      - description: Session key
        in: path
        name: session
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Session deleted
        "400":
          description: Received bad request body
          schema:
            $ref: '#/definitions/models.RequestError'
        "404":
          description: Session not found
          schema:
            $ref: '#/definitions/models.RequestError'
      summary: Delete session by provided key
      tags:
      - sessions
    get:
      parameters:
      - description: Session key
        in: path
        name: session
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Session is valid
        "400":
          description: Received bad request body
          schema:
            $ref: '#/definitions/models.RequestError'
        "401":
          description: Session is invalid
          schema:
            $ref: '#/definitions/models.RequestError'
      summary: Authenticate user with session key
      tags:
      - sessions
swagger: "2.0"
